---
- hosts: node_exporter
  become: yes
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - consul_install

- hosts: bootstrap
  become: yes
  become_method: sudo
  roles:
    - consul_bootstrap

- hosts: consul_agent
  become: yes
  become_method: sudo
  roles:
    - consul_client