---
- hosts: node_exporter
  become: yes
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: consul_agent
  become: yes
  become_method: sudo
  roles:
    - consul_install
    - consul_configure
