- name: Install yum-utils to get yum-config-manager command
  yum:
    name: "yum-utils"
    state: present
  when: ansible_facts['os_family'] != "Debian"

- name: Add the repo
  get_url:
    url: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
    dest: "/etc/yum.repos.d/hashicorp.repo"
    mode: "0640"
  when: ansible_facts['os_family'] != "Debian"


- name: Add consul repo key on ubuntu
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    state: present
  when: ansible_facts['os_family'] == "Debian"


- name: Add consul repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com bionic main"
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: install latest consul on ubuntu
  apt:
    name: consul
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Installing consul latest package on rhel
  yum:
    name: "consul"
    state: present
  when: latest == true and ansible_facts['os_family'] != "Debian"

- name: Install the specific version of consul package
  yum:
    name: "consul-{{ version }}.x86_64"
  when: latest != true and ansible_facts['os_family'] != "Debian"

- name: Verify If consul is installed
  command: "consul --version"
  register: consul_version

- assert:
    that:
    - "'Consul' in consul_version.stdout"

- name: Generate the consul encryption key
  command: "consul keygen"
  register: consul_key
  run_once: true

- name: Create consul agent config dirs
  file:
     path: "{{ consul_config_dir }}"
     state: directory
     mode: 0750
     owner: "{{ consul_username }}"
     group: "{{ consul_groupname }}"

- name: Create consul agent config dirs
  file:
     path: "{{ consul_data_dir }}"
     state: directory
     mode: 0750
     owner: "{{ consul_username }}"
     group: "{{ consul_groupname }}"
     recurse: true

- name: Adding the firewall rule
  firewalld:
    port: "{{  item }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_facts['os_family'] != "Debian"
  loop:
      - 8500
      - 8300
      - 8301
      - 8302
      - 8600

- name: Firewall rule for Ubuntu System
  ufw:
    port: "{{ item }}"
    proto: tcp
    rule: allow
  when: ansible_facts['os_family'] == "Debian"
  loop:
      - 8500
      - 8300
      - 8301
      - 8302
      - 8600
