- name: Install yum-utils to get yum-config-manager command
  yum:
    name: "yum-utils"
    state: present
  when: ansible_facts['os_family'] != "Debian"

- name: Add the repo
  command: "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
  changed_when: true
  when: ansible_facts['os_family'] != "Debian"

- name: Add consul repo key on ubuntu
  shell: "curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -"
  changed_when: true
  when: ansible_facts['os_family'] == "Debian"

- name: Add consul repo
  shell: "apt-add-repository 'deb [arch=amd64] https://apt.releases.hashicorp.com bionic main'"
  changed_when: true
  become: true
  ignore_errors: true
  when: ansible_facts['os_family'] == "Debian"

- name: install consul
  apt:
    name: consul
    state: present
  when: ansible_facts['os_family'] == "Debian"

  
# - name: Add repository
#   yum_repository:
#     name: Consul
#     description: Consul Hashicorp Repo
#     baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
#   when: ansible_facts['os_family'] != "Debian"

- name: Installing consul latest package
  yum:
    name: "consul"
    state: present
  when: latest == true and ansible_facts['os_family'] != "Debian"

- name: Install the specific version of consul package
  yum:
    name: "consul-{{ version }}.x86_64"
  when: latest != true and ansible_facts['os_family'] != "Debian"

- name: Verify If consul is installed
  command: "consul --version"
  register: consul_version
  # failed_when: "'FAILED' in command_result.stderr"

- assert:
    that:
    - "'Consul' in consul_version.stdout"

- name: Generate the consul encryption key
  command: "consul keygen"
  register: consul_key

- name: Create consul agent config dirs
  file:
     path: "{{ consul_config_dir }}"
     state: directory
     mode: 0750
     owner: "{{ consul_username }}"
     group: "{{ consul_groupname }}"

- name: Create consul agent config dirs
  file:
     path: "{{ consul_data_dir }}"
     state: directory
     mode: 0750
     owner: "{{ consul_username }}"
     group: "{{ consul_groupname }}"
     recurse: true

- name: Adding the firewall rule
  firewalld:
    port: "{{  item }}/tcp"
    state: enabled
    permanent: yes
    immediate: yes
  when: ansible_facts['os_family'] != "Debian"
  loop:
      - 8500
      - 8300
      - 8301
      - 8302
      - 8600

- name: Firewall rule for Ubuntu System
  ufw:
    port: "{{ item }}"
    proto: tcp
    rule: allow
  when: ansible_facts['os_family'] == "Debian"
  loop:
      - 8500
      - 8300
      - 8301
      - 8302
      - 8600

# - name: Start the consule service
#   shell: "(consul agent --config-dir={{ consul_config_dir }}/  &)"
#   tags:
#     - start_consul
